version: '3.8'
services:
  selenium:
    image: selenium/standalone-chrome:117.0
    ports:
      - "4444:4444"
    shm_size: '2gb'
  test-runner:
    build:
      context: .
      dockerfile: docker/Dockerfile.test-runner
    environment:
      - BASE_URL=${BASE_URL:-https://demo-ecommerce.example}
      - SELENIUM_GRID_URL=http://selenium:4444
    depends_on:
      - selenium
    volumes:
      - ./logs:/app/logs
  log-viewer:
    image: busybox
    command: /bin/sh -c "tail -F /app/logs/test.log"
    volumes:
      - ./logs:/app/logs
